import io
import logging
import os
import tempfile
from datetime import timedelta

import qrcode
from celery import shared_task
from django.core.mail import EmailMessage
from django.utils import timezone
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas

logger = logging.getLogger(__name__)

EVENTS_CACHE_KEY = "ticketpulse:events:list"


@shared_task(bind=True, max_retries=3, default_retry_delay=60)
def send_booking_confirmation(self, booking_id: int) -> str:

    from apps.events.models import Booking

    try:
        booking = Booking.objects.select_related(
            "user", "event"
        ).prefetch_related("tickets").get(id=booking_id)

    except Booking.DoesNotExist:
        logger.error("Booking #%s not found", booking_id)
        return f"Booking {booking_id} not found"

    try:
        # Step 1 — Generate QR Code
        qr_data = (
            f"TICKETPULSE"
            f"|BOOKING:{booking.id}"
            f"|EVENT:{booking.event.title}"
            f"|USER:{booking.user.email}"
            f"|TOTAL:{booking.total_price}"
        )
        qr_image = qrcode.make(qr_data)
        qr_temp = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
        qr_image.save(qr_temp.name)
        qr_temp.close()
        qr_path = qr_temp.name

        # Step 2 — Generate PDF
        pdf_buffer = io.BytesIO()
        pdf = canvas.Canvas(pdf_buffer, pagesize=A4)
        width, height = A4

        # Header
        pdf.setFillColorRGB(0.13, 0.13, 0.72)
        pdf.rect(0, height - 90, width, 90, fill=True, stroke=False)
        pdf.setFillColorRGB(1, 1, 1)
        pdf.setFont("Helvetica-Bold", 30)
        pdf.drawCentredString(width / 2, height - 45, "TICKETPULSE")
        pdf.setFont("Helvetica", 12)
        pdf.drawCentredString(width / 2, height - 68, "Official Event Ticket")

        # Booking details
        pdf.setFillColorRGB(0, 0, 0)
        pdf.setFont("Helvetica-Bold", 16)
        pdf.drawCentredString(width / 2, height - 120, booking.event.title)

        pdf.setFont("Helvetica", 12)
        y = height - 160
        details = [
            f"Booking ID : #{booking.id}",
            f"Customer   : {booking.user.username}",
            f"Email      : {booking.user.email}",
            f"Event Date : {booking.event.date.strftime('%B %d, %Y at %H:%M UTC')}",
            f"Location   : {booking.event.location}",
            f"Total Paid : NPR {booking.total_price}",
            f"Status     : {booking.status}",
        ]
        for line in details:
            pdf.drawString(3 * cm, y, line)
            y -= 28

        # Seats
        y -= 10
        pdf.setFont("Helvetica-Bold", 12)
        pdf.drawString(3 * cm, y, "Booked Seats:")
        y -= 22
        pdf.setFont("Helvetica", 12)
        for ticket in booking.tickets.all():
            pdf.drawString(
                4 * cm, y,
                f"Seat {ticket.seat_number} — NPR {ticket.price}"
            )
            y -= 22

        # QR Code
        y -= 20
        pdf.drawImage(qr_path, width / 2 - 75, y - 150, width=150, height=150)
        pdf.setFont("Helvetica", 9)
        pdf.drawCentredString(
            width / 2, y - 165,
            "Scan this QR code at the venue entrance",
        )

        # Footer
        pdf.setFont("Helvetica", 8)
        pdf.setFillColorRGB(0.5, 0.5, 0.5)
        pdf.drawCentredString(
            width / 2, 1.5 * cm,
            f"Generated by TicketPulse on "
            f"{timezone.now().strftime('%Y-%m-%d %H:%M UTC')}",
        )

        pdf.save()
        pdf_buffer.seek(0)

        # Clean up temp QR file
        os.unlink(qr_path)

        # Step 3 — Send Email
        email = EmailMessage(
            subject=f"Booking Confirmed — {booking.event.title}",
            body=(
                f"Hi {booking.user.username},\n\n"
                f"Your booking is confirmed!\n\n"
                f"Event   : {booking.event.title}\n"
                f"Booking : #{booking.id}\n"
                f"Total   : NPR {booking.total_price}\n\n"
                f"Your PDF ticket is attached.\n"
                f"Show it at the venue entrance.\n\n"
                f"See you there!\n"
                f"— TicketPulse Team"
            ),
            from_email="noreply@ticketpulse.com",
            to=[booking.user.email],
        )
        email.attach(
            filename=f"ticket_{booking.id}.pdf",
            content=pdf_buffer.getvalue(),
            mimetype="application/pdf",
        )
        email.send()

        logger.info(
            "Confirmation email sent for booking #%s to %s",
            booking.id,
            booking.user.email,
        )
        return f"Confirmation sent for booking #{booking.id}"

    except Exception as exc:
        logger.error(
            "Task failed for booking #%s: %s",
            booking_id,
            str(exc),
            exc_info=True,
        )
        raise self.retry(exc=exc)


@shared_task
def expire_pending_bookings() -> str:
    

    from apps.events.models import Booking, Event, Ticket
    from django.core.cache import cache

    cutoff_time = timezone.now() - timedelta(minutes=10)

    expired = Booking.objects.filter(
        status=Booking.Status.PENDING,
        created_at__lt=cutoff_time,
    ).select_related("event").prefetch_related("tickets")

    count = 0

    for booking in expired:
        ticket_count = booking.tickets.count()

        booking.tickets.update(status=Ticket.Status.AVAILABLE)

        Event.objects.filter(pk=booking.event.pk).update(
            available_tickets=booking.event.available_tickets + ticket_count
        )

        booking.status = Booking.Status.EXPIRED
        booking.save(update_fields=["status", "updated_at"])

        cache.delete(EVENTS_CACHE_KEY)

        count += 1
        logger.info(
            "Booking #%s expired — %s seats returned to pool",
            booking.id,
            ticket_count,
        )

    if count > 0:
        logger.info("Total expired this run: %s bookings", count)

    return f"Expired {count} bookings"